
spring:
  datasource:
    url: jdbc:sqlserver://(localdb)\\MSSQLLocalDB;databaseName=ApologeticsCrucible;encrypt=false;trustServerCertificate=true;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  # Disable Spring Data JDBC auto-config (we use our own stored procedures)
  data:
    jdbc:
      repositories:
        enabled: false

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.microsoft.sqlserver: DEBUG